
var f;f||(f=typeof Module !== 'undefined' ? Module : {});f.dc||(f.dc=0);f.dc++;
(function(a){function b(n,t,r,w){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(h,u){h?w(h):r(u.buffer)});else{var v=new XMLHttpRequest;v.open("GET",n,!0);v.responseType="arraybuffer";v.onprogress=function(h){var u=t;h.total&&(u=h.total);if(h.loaded){v.ub?f.Cb[n].loaded=h.loaded:(v.ub=!0,f.Cb||(f.Cb={}),f.Cb[n]={loaded:h.loaded,total:u});var y=u=h=0,A;for(A in f.Cb){var R=f.Cb[A];h+=R.total;u+=R.loaded;y++}h=
Math.ceil(h*f.dc/y);f.setStatus&&f.setStatus("Downloading data... ("+u+"/"+h+")")}else!f.Cb&&f.setStatus&&f.setStatus("Downloading data...")};v.onerror=function(){throw Error("NetworkError for: "+n);};v.onload=function(){if(200==v.status||304==v.status||206==v.status||0==v.status&&v.response)r(v.response);else throw Error(v.statusText+" : "+v.responseURL);};v.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(v,h,u){this.start=v;this.end=h;this.audio=u}function t(v){if(!v)throw"Loading data file failed."+
Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);n.prototype.cd=v;v=a.files;for(var h=0;h<v.length;++h)n.prototype.ub[v[h].filename].onload();f.removeRunDependency("datafile_/RamDisk/emsOut/MinSizeRel/wglApp.data")}f.FS_createPath("/","Shaders",!0,!0);n.prototype={ub:{},open:function(v,h){this.name=h;this.ub[h]=this;f.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.jc(this.cd.subarray(this.start,this.end))},
jc:function(v){f.FS_createDataFile(this.name,null,v,!0,!0,!0);f.removeRunDependency("fp "+this.name);this.ub[this.name]=null}};for(var r=a.files,w=0;w<r.length;++w)(new n(r[w].start,r[w].end,r[w].audio||0)).open("GET",r[w].filename);f.addRunDependency("datafile_/RamDisk/emsOut/MinSizeRel/wglApp.data");f.Ec||(f.Ec={});f.Ec["/RamDisk/emsOut/MinSizeRel/wglApp.data"]={Ad:!1};m?(t(m),m=null):k=t}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof f.locateFilePackage||f.locateFile||(f.locateFile=f.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=f.locateFile?f.locateFile("wglApp.data",""):"wglApp.data",g=a.remote_package_size,k=null,m=f.getPreloadedPackage?
f.getPreloadedPackage(e,g):null;m||b(e,g,function(n){k?(k(n),k=null):m=n},c);f.calledRun?d():(f.preRun||(f.preRun=[]),f.preRun.push(d))})({files:[{filename:"/Shaders/colorSpaces.glsl",start:0,end:4903},{filename:"/Shaders/frag.glsl",start:4903,end:15307},{filename:"/Shaders/vert.glsl",start:15307,end:15646},{filename:"/Shaders/frag_test.glsl",start:15646,end:32706},{filename:"/image0.png",start:32706,end:2587564},{filename:"/image1.png",start:2587564,end:4751888},{filename:"/image2.png",start:4751888,
end:6993237}],remote_package_size:6993237,package_uuid:"5076f35e-c4ed-4c5a-8c3b-007d593e24ae"});var aa={},p;for(p in f)f.hasOwnProperty(p)&&(aa[p]=f[p]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea="object"===typeof window,fa="function"===typeof importScripts,ha="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,q="",ia,ja,ka,la,ma;
if(ha)q=fa?require("path").dirname(q)+"/":__dirname+"/",ia=function(a,b){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);return la.readFileSync(a,b?null:"utf8")},ka=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},ja=function(a,b,c){la||(la=require("fs"));ma||(ma=require("path"));a=ma.normalize(a);la.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==
typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof na))throw a;}),process.on("unhandledRejection",function(a){throw a;}),da=function(a,b){if(noExitRuntime||0<oa)throw process.exitCode=a,b;b instanceof na||l("exiting due to exception: "+b);process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ea||fa)fa?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?
q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};
var x=f.print||console.log.bind(console),l=f.printErr||console.warn.bind(console);for(p in aa)aa.hasOwnProperty(p)&&(f[p]=aa[p]);aa=null;f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);f.quit&&(da=f.quit);function pa(a){qa||(qa={});qa[a]||(qa[a]=1,l(a))}var qa,sa;f.wasmBinary&&(sa=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");
function B(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":C[a>>0]=b;break;case "i8":C[a>>0]=b;break;case "i16":ta[a>>1]=b;break;case "i32":D[a>>2]=b;break;case "i64":ua=[b>>>0,(E=b,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];D[a>>2]=ua[0];D[a+4>>2]=ua[1];break;case "float":va[a>>2]=b;break;case "double":wa[a>>3]=b;break;default:z("invalid type for setValue: "+c)}}var xa,ya=!1,za;
function assert(a,b){a||z("Assertion failed: "+b)}function Aa(a){var b=Ba(a.length);a.subarray||a.slice?F.set(a,b):F.set(new Uint8Array(a),b);return b}var Ca="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Da(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Ea(a,b){return a?Da(F,a,b):""}
function Fa(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var m=a.charCodeAt(++g);k=65536+((k&1023)<<10)|m&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=Ia(b);Fa(a,C,c,b);return c}var Ja,C,F,ta,Ka,D,La,va,wa;
function Ma(){var a=xa.buffer;Ja=a;f.HEAP8=C=new Int8Array(a);f.HEAP16=ta=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=Ka=new Uint16Array(a);f.HEAPU32=La=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=wa=new Float64Array(a)}var Na,Oa=[],Pa=[],Qa=[],Ra=[],Sa=!1,oa=0;function Ta(){var a=f.preRun.shift();Oa.unshift(a)}var Ua=0,Va=null,Wa=null;function Xa(){Ua++;f.monitorRunDependencies&&f.monitorRunDependencies(Ua)}
function Ya(){Ua--;f.monitorRunDependencies&&f.monitorRunDependencies(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}f.preloadedImages={};f.preloadedAudios={};function z(a){if(f.onAbort)f.onAbort(a);a="Aborted("+a+")";l(a);ya=!0;za=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}function Za(){return G.startsWith("data:application/octet-stream;base64,")}var G;G="wglApp.wasm";
if(!Za()){var $a=G;G=f.locateFile?f.locateFile($a,q):q+$a}function ab(){var a=G;try{if(a==G&&sa)return new Uint8Array(sa);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function bb(){if(!sa&&(ea||fa)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return ab()});if(ja)return new Promise(function(a,b){ja(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ab()})}var E,ua;
function cb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.Vc;"number"===typeof c?void 0===b.Mb?H(c)():H(c)(b.Mb):c(void 0===b.Mb?null:b.Mb)}}}function H(a){return Na.get(a)}function db(a){a instanceof na||"unwind"==a||da(1,a)}
function eb(a){this.Fb=a-16;this.md=function(b){D[this.Fb+4>>2]=b};this.jd=function(b){D[this.Fb+8>>2]=b};this.kd=function(){D[this.Fb>>2]=0};this.hd=function(){C[this.Fb+12>>0]=0};this.ld=function(){C[this.Fb+13>>0]=0};this.Xc=function(b,c){this.md(b);this.jd(c);this.kd();this.hd();this.ld()}}var fb=0;function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function I(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";a=I(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){z("randomDevice")}}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var lb=[];function mb(a,b){lb[a]={input:[],output:[],Eb:b};nb(a,ob)}
var ob={open:function(a){var b=lb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Eb.flush(a.tty)},flush:function(a){a.tty.Eb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Eb.wc)throw new J(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Eb.wc(a.tty)}catch(m){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Eb.kc)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.Eb.kc(a.tty,b[c+e])}catch(g){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},qb={wc:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),d=0;try{d=la.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},kc:function(a,b){null===b||10===b?(x(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(x(Da(a.output,0)),a.output=[])}},rb={kc:function(a,b){null===b||10===b?(l(Da(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(l(Da(a.output,0)),a.output=[])}},L={vb:null,wb:function(){return L.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);L.vb||(L.vb={dir:{node:{yb:L.pb.yb,tb:L.pb.tb,lookup:L.pb.lookup,Ub:L.pb.Ub,rename:L.pb.rename,unlink:L.pb.unlink,rmdir:L.pb.rmdir,readdir:L.pb.readdir,symlink:L.pb.symlink},stream:{zb:L.qb.zb}},file:{node:{yb:L.pb.yb,tb:L.pb.tb},stream:{zb:L.qb.zb,read:L.qb.read,write:L.qb.write,nc:L.qb.nc,Ac:L.qb.Ac,Cc:L.qb.Cc}},link:{node:{yb:L.pb.yb,tb:L.pb.tb,readlink:L.pb.readlink},stream:{}},pc:{node:{yb:L.pb.yb,tb:L.pb.tb},
stream:sb}});c=tb(a,b,c,d);16384===(c.mode&61440)?(c.pb=L.vb.dir.node,c.qb=L.vb.dir.stream,c.ob={}):32768===(c.mode&61440)?(c.pb=L.vb.file.node,c.qb=L.vb.file.stream,c.rb=0,c.ob=null):40960===(c.mode&61440)?(c.pb=L.vb.link.node,c.qb=L.vb.link.stream):8192===(c.mode&61440)&&(c.pb=L.vb.pc.node,c.qb=L.vb.pc.stream);c.timestamp=Date.now();a&&(a.ob[b]=c,a.timestamp=c.timestamp);return c},Bd:function(a){return a.ob?a.ob.subarray?a.ob.subarray(0,a.rb):new Uint8Array(a.ob):new Uint8Array(0)},sc:function(a,
b){var c=a.ob?a.ob.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ob,a.ob=new Uint8Array(b),0<a.rb&&a.ob.set(c.subarray(0,a.rb),0))},ed:function(a,b){if(a.rb!=b)if(0==b)a.ob=null,a.rb=0;else{var c=a.ob;a.ob=new Uint8Array(b);c&&a.ob.set(c.subarray(0,Math.min(b,a.rb)));a.rb=b}},pb:{yb:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.rb:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Qc=4096;b.blocks=Math.ceil(b.size/b.Qc);return b},tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&L.ed(a,b.size)},lookup:function(){throw ub[44];},Ub:function(a,b,c,d){return L.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=vb(b,c)}catch(g){}if(d)for(var e in d.ob)throw new J(55);
}delete a.parent.ob[a.name];a.parent.timestamp=Date.now();a.name=c;b.ob[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.ob[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=vb(a,b),d;for(d in c.ob)throw new J(55);delete a.ob[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.ob)a.ob.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=L.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);
return a.link}},qb:{read:function(a,b,c,d,e){var g=a.node.ob;if(e>=a.node.rb)return 0;a=Math.min(a.node.rb-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===C.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ob||a.ob.subarray)){if(g)return a.ob=b.subarray(c,c+d),a.rb=d;if(0===a.rb&&0===e)return a.ob=b.slice(c,c+d),a.rb=d;if(e+d<=a.rb)return a.ob.set(b.subarray(c,c+d),e),d}L.sc(a,e+
d);if(a.ob.subarray&&b.subarray)a.ob.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ob[e+g]=b[c+g];a.rb=Math.max(a.rb,e+d);return d},zb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.rb);if(0>b)throw new J(28);return b},nc:function(a,b,c){L.sc(a.node,b+c);a.node.rb=Math.max(a.node.rb,b+c)},Ac:function(a,b,c,d,e,g){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.ob;if(g&2||a.buffer!==Ja){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;z();c=void 0;if(!c)throw new J(48);C.set(a,c)}else d=!1,c=a.byteOffset;return{Fb:c,ud:d}},Cc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;L.qb.write(a,b,0,d,c,!1);return 0}}};function wb(a,b,c){var d="al "+a;ja(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Ya(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Xa(d)}
var xb=null,yb={},zb=[],Ab=1,M=null,Bb=!0,J=null,ub={};
function N(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={tc:!0,lc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.lc)throw new J(32);a=gb(a.split("/").filter(function(k){return!!k}),!1);var e=xb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=vb(e,a[d]);c=I(c+"/"+a[d]);e.Jb&&(!g||g&&b.tc)&&(e=e.Jb.root);if(!g||b.ec)for(g=0;40960===(e.mode&61440);)if(e=Cb(c),c=kb(hb(c),e),e=N(c,{lc:b.lc}).node,40<g++)throw new J(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.wb.Bc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%M.length}function vb(a,b){var c;if(c=(c=Fb(a,"x"))?c:a.pb.lookup?0:2)throw new J(c,a);for(c=M[Eb(a.id,b)];c;c=c.Db){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.pb.lookup(a,b)}
function tb(a,b,c,d){a=new Gb(a,b,c,d);b=Eb(a.parent.id,a.name);a.Db=M[b];return M[b]=a}var Hb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Fb(a,b){if(Bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Jb(a,b){try{return vb(a,b),20}catch(c){}return Fb(a,"wx")}
function Kb(a){var b=4096;for(a=a||0;a<=b;a++)if(!zb[a])return a;throw new J(33);}function Lb(a,b){Mb||(Mb=function(){},Mb.prototype={});var c=new Mb,d;for(d in a)c[d]=a[d];a=c;b=Kb(b);a.fd=b;return zb[b]=a}var sb={open:function(a){a.qb=yb[a.node.rdev].qb;a.qb.open&&a.qb.open(a)},zb:function(){throw new J(70);}};function nb(a,b){yb[a]={qb:b}}
function Nb(a,b){var c="/"===b,d=!b;if(c&&xb)throw new J(10);if(!c&&!d){var e=N(b,{tc:!1});b=e.path;e=e.node;if(e.Jb)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,Id:{},Bc:b,bd:[]};a=a.wb(b);a.wb=b;b.root=a;c?xb=a:e&&(e.Jb=b,e.wb&&e.wb.bd.push(b))}function Ob(a,b,c){var d=N(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new J(28);var e=Jb(d,a);if(e)throw new J(e);if(!d.pb.Ub)throw new J(63);return d.pb.Ub(d,a,b,c)}function O(a){return Ob(a,16895,0)}
function Pb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Ob(a,b|8192,c)}function Qb(a,b){if(!kb(a))throw new J(44);var c=N(b,{parent:!0}).node;if(!c)throw new J(44);b=ib(b);var d=Jb(c,b);if(d)throw new J(d);if(!c.pb.symlink)throw new J(63);c.pb.symlink(c,b,a)}
function Rb(a){var b=N(a,{parent:!0}).node,c=ib(a);a=vb(b,c);a:{try{var d=vb(b,c)}catch(g){d=g.xb;break a}var e=Fb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new J(d);if(!b.pb.unlink)throw new J(63);if(a.Jb)throw new J(10);b.pb.unlink(b,c);b=Eb(a.parent.id,a.name);if(M[b]===a)M[b]=a.Db;else for(b=M[b];b;){if(b.Db===a){b.Db=a.Db;break}b=b.Db}}function Cb(a){a=N(a).node;if(!a)throw new J(44);if(!a.pb.readlink)throw new J(28);return kb(Db(a.parent),a.pb.readlink(a))}
function Sb(a,b){a="string"===typeof a?N(a,{ec:!0}).node:a;if(!a.pb.tb)throw new J(63);a.pb.tb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Tb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Hb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=I(a);try{g=N(a,{ec:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(g){if(b&128)throw new J(20);}else g=Ob(a,c,0),e=!0;if(!g)throw new J(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new J(54);if(!e&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Ib(b)||b&512)?31:Fb(g,Ib(b)):44))throw new J(c);if(b&512){c=g;c="string"===typeof c?N(c,{ec:!0}).node:c;if(!c.pb.tb)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Fb(c,"w"))throw new J(e);c.pb.tb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Lb({node:g,path:Db(g),id:g.id,flags:b,mode:g.mode,seekable:!0,position:0,qb:g.qb,pb:g.pb,rd:[],error:!1},d);d.qb.open&&d.qb.open(d);!f.logReadFiles||b&1||(Ub||(Ub={}),
a in Ub||(Ub[a]=1));return d}function Vb(a){if(null===a.fd)throw new J(8);a.hc&&(a.hc=null);try{a.qb.close&&a.qb.close(a)}catch(b){throw b;}finally{zb[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.qb.zb)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.qb.zb(a,b,c);a.rd=[]}
function Xb(a,b,c,d,e,g){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.qb.write)throw new J(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new J(70);b=a.qb.write(a,b,c,d,e,g);k||(a.position+=b);return b}
function Yb(){J||(J=function(a,b){this.node=b;this.gd=function(c){this.xb=c};this.gd(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){ub[a]=new J(a);ub[a].stack="<generic error, no stack>"}))}var Zb;function $b(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function ac(a,b){a="string"===typeof a?a:Db(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=I(a+"/"+c);try{O(d)}catch(e){}a=d}}return d}
function bc(a,b,c,d){a=I(("string"===typeof a?a:Db(a))+"/"+b);c=$b(c,d);return Ob(a,(void 0!==c?c:438)&4095|32768,0)}function cc(a,b,c,d,e,g){a=b?I(("string"===typeof a?a:Db(a))+"/"+b):a;d=$b(d,e);e=Ob(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Sb(e,d|146);a=Tb(e,577);Xb(a,c,0,c.length,0,g);Vb(a);Sb(e,d)}return e}
function P(a,b,c,d){a=I(("string"===typeof a?a:Db(a))+"/"+b);b=$b(!!c,!!d);P.yc||(P.yc=64);var e=P.yc++<<8|0;nb(e,{open:function(g){g.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(g,k,m,n){for(var t=0,r=0;r<n;r++){try{var w=c()}catch(v){throw new J(29);}if(void 0===w&&0===t)throw new J(6);if(null===w||void 0===w)break;t++;k[m+r]=w}t&&(g.node.timestamp=Date.now());return t},write:function(g,k,m,n){for(var t=0;t<n;t++)try{d(k[m+t])}catch(r){throw new J(29);}n&&(g.node.timestamp=
Date.now());return t}});return Pb(a,b,e)}function dc(a){if(!(a.$c||a.ad||a.link||a.ob)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ia)try{a.ob=pb(ia(a.url),!0),a.rb=a.ob.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ec(a,b,c,d,e){function g(){this.ic=!1;this.ub=[]}g.prototype.get=function(r){if(!(r>this.length-1||0>r)){var w=r%this.chunkSize;return this.xc(r/this.chunkSize|0)[w]}};g.prototype.jc=function(r){this.xc=r};g.prototype.oc=function(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var w=Number(r.getResponseHeader("Content-length")),v,h=(v=r.getResponseHeader("Accept-Ranges"))&&
"bytes"===v;r=(v=r.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;h||(u=w);var y=this;y.jc(function(A){var R=A*u,ra=(A+1)*u-1;ra=Math.min(ra,w-1);if("undefined"===typeof y.ub[A]){var de=y.ub;if(R>ra)throw Error("invalid range ("+R+", "+ra+") or no bytes requested!");if(ra>w-1)throw Error("only "+w+" bytes available! programmer error!");var K=new XMLHttpRequest;K.open("GET",c,!1);w!==u&&K.setRequestHeader("Range","bytes="+R+"-"+ra);"undefined"!=typeof Uint8Array&&(K.responseType=
"arraybuffer");K.overrideMimeType&&K.overrideMimeType("text/plain; charset=x-user-defined");K.send(null);if(!(200<=K.status&&300>K.status||304===K.status))throw Error("Couldn't load "+c+". Status: "+K.status);R=void 0!==K.response?new Uint8Array(K.response||[]):pb(K.responseText||"",!0);de[A]=R}if("undefined"===typeof y.ub[A])throw Error("doXHR failed!");return y.ub[A]});if(r||!w)u=w=1,u=w=this.xc(0).length,x("LazyFiles on gzip forces download of the whole file when length is accessed");this.Oc=w;
this.Nc=u;this.ic=!0};if("undefined"!==typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new g;Object.defineProperties(k,{length:{get:function(){this.ic||this.oc();return this.Oc}},chunkSize:{get:function(){this.ic||this.oc();return this.Nc}}});var m=void 0}else m=c,k=void 0;var n=bc(a,b,d,e);k?n.ob=k:m&&(n.ob=null,n.url=m);Object.defineProperties(n,{rb:{get:function(){return this.ob.length}}});
var t={};Object.keys(n.qb).forEach(function(r){var w=n.qb[r];t[r]=function(){dc(n);return w.apply(null,arguments)}});t.read=function(r,w,v,h,u){dc(n);r=r.node.ob;if(u>=r.length)return 0;h=Math.min(r.length-u,h);if(r.slice)for(var y=0;y<h;y++)w[v+y]=r[u+y];else for(y=0;y<h;y++)w[v+y]=r.get(u+y);return h};n.qb=t;return n}
function fc(a,b,c,d,e,g,k,m,n,t){function r(h){function u(A){t&&t();m||cc(a,b,A,d,e,n);g&&g();Ya(v)}var y=!1;f.preloadPlugins.forEach(function(A){!y&&A.canHandle(w)&&(A.handle(h,w,u,function(){k&&k();Ya(v)}),y=!0)});y||u(h)}gc();var w=b?kb(I(a+"/"+b)):a,v="cp "+w;Xa(v);"string"==typeof c?wb(c,function(h){r(h)},k):r(c)}var hc={},Mb,Ub,ic=void 0;function jc(){ic+=4;return D[ic-4>>2]}function kc(a){a=zb[a];if(!a)throw new J(8);return a}function lc(a){if(!Sa&&!ya)try{a()}catch(b){db(b)}}
function mc(a){setTimeout(function(){lc(a)},1E4)}var nc=!1,oc=null,pc=0,qc=null,rc=0,sc=0,tc=0,uc=0,vc=[],wc={},xc,yc,zc,Ac=!1,Bc=!1,Cc=[];
function gc(){function a(){Bc=document.pointerLockElement===f.canvas||document.mozPointerLockElement===f.canvas||document.webkitPointerLockElement===f.canvas||document.msPointerLockElement===f.canvas}f.preloadPlugins||(f.preloadPlugins=[]);if(!Dc){Dc=!0;try{Ec=!0}catch(c){Ec=!1,x("warning: no blob constructor, cannot create blobs with mimetypes")}Fc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Ec?null:x("warning: no BlobBuilder");Gc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;f.Dc||"undefined"!==typeof Gc||(x("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),f.Dc=!0);f.preloadPlugins.push({canHandle:function(c){return!f.Dc&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var k=null;if(Ec)try{k=new Blob([c],{type:Hc(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:Hc(d)}))}catch(t){pa("Blob constructor present but fails: "+
t+"; falling back to blob builder")}k||(k=new Fc,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var m=Gc.createObjectURL(k),n=new Image;n.onload=function(){assert(n.complete,"Image "+d+" could not be decoded");var t=document.createElement("canvas");t.width=n.width;t.height=n.height;t.getContext("2d").drawImage(n,0,0);f.preloadedImages[d]=t;Gc.revokeObjectURL(m);e&&e(c)};n.onerror=function(){x("Image "+m+" could not be decoded");g&&g()};n.src=m}});f.preloadPlugins.push({canHandle:function(c){return!f.Hd&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,g){function k(w){n||(n=!0,f.preloadedAudios[d]=w,e&&e(c))}function m(){n||(n=!0,f.preloadedAudios[d]=new Audio,g&&g())}var n=!1;if(Ec){try{var t=new Blob([c],{type:Hc(d)})}catch(w){return m()}t=Gc.createObjectURL(t);var r=new Audio;r.addEventListener("canplaythrough",function(){k(r)},!1);r.onerror=function(){if(!n){x("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var w="",v=0,h=0,u=0;u<c.length;u++)for(v=
v<<8|c[u],h+=8;6<=h;){var y=v>>h-6&63;h-=6;w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[y]}2==h?(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],w+="=="):4==h&&(w+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],w+="=");r.src="data:audio/x-"+d.substr(-3)+";base64,"+w;k(r)}};r.src=t;mc(function(){k(r)})}else return m()}});var b=f.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),f.elementPointerLock&&b.addEventListener("click",
function(c){!Bc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Ic(a,b,c,d){if(b&&f.Ab&&a==f.canvas)return f.Ab;var e;if(b){var g={antialias:!1,alpha:!1,zc:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)g[k]=d[k];if("undefined"!==typeof Jc&&(e=Kc(a,g)))var m=Lc[e].Ib}else m=a.getContext("2d");if(!m)return null;c&&(b||assert("undefined"===typeof Q,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),f.Ab=m,b&&(S=Lc[e],f.Ab=Q=S&&S.Ib),f.Kd=b,Cc.forEach(function(n){n()}),gc());return m}
var Mc=!1,Nc=void 0,Oc=void 0;
function Pc(a,b){function c(){Ac=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Qc,Nc&&d.requestPointerLock(),Ac=!0,Oc?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=La[SDL.screen>>2]|8388608),Rc(f.canvas),Sc()):Rc(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),Oc?("undefined"!=typeof SDL&&(D[SDL.screen>>2]=La[SDL.screen>>2]&
-8388609),Rc(f.canvas),Sc()):Rc(d));if(f.onFullScreen)f.onFullScreen(Ac);if(f.onFullscreen)f.onFullscreen(Ac)}Nc=a;Oc=b;"undefined"===typeof Nc&&(Nc=!0);"undefined"===typeof Oc&&(Oc=!1);var d=f.canvas;Mc||(Mc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Qc(){if(!Ac)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Tc=0;function Uc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Tc)Tc=b+1E3/60;else for(;b+2>=Tc;)Tc+=1E3/60;setTimeout(a,Math.max(Tc-b,0))}}
function Hc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Vc=0,Wc=0,Xc=0,Yc=0;
function Zc(a){if(Bc)"mousemove"!=a.type&&"mozMovementX"in a?Xc=Yc=0:(Xc=a.movementX||a.mozMovementX||a.webkitMovementX||0,Yc=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Vc=SDL.Ed+Xc,Wc=SDL.Fd+Yc):(Vc+=Xc,Wc+=Yc);else{var b=f.canvas.getBoundingClientRect(),c=f.canvas.width,d=f.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,g="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(g+b.top),e*=c/b.width,a*=d/b.height,Xc=e-Vc,Yc=a-Wc,Vc=e,Wc=a)}}var $c=[];function Sc(){var a=f.canvas;$c.forEach(function(b){b(a.width,a.height)})}function ad(a,b,c){Rc(f.canvas,a,b);c||Sc()}
function Rc(a,b,c){b&&c?(a.sd=b,a.Wc=c):(b=a.sd,c=a.Wc);var d=b,e=c;f.forcedAspectRatio&&0<f.forcedAspectRatio&&(d/e<f.forcedAspectRatio?d=Math.round(e*f.forcedAspectRatio):e=Math.round(d/f.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}Oc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Dc,Ec,Fc,Gc;
function bd(a,b){sc=a;tc=b;if(qc)if(nc||(nc=!0),0==a)oc=function(){var d=Math.max(0,yc+b-cd())|0;setTimeout(zc,d)};else if(1==a)oc=function(){Uc(zc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);fa?(void 0===f.setImmediates&&(f.setImmediates=[]),f.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}oc=function(){setImmediate(zc)}}}var cd;cd=ha?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
function dd(a,b,c,d,e){function g(){if(k<pc){if(!(noExitRuntime||0<oa))try{ed(za)}catch(m){db(m)}return!1}return!0}assert(!qc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");qc=a;rc=d;var k=pc;nc=!1;zc=function(){if(!ya)if(0<vc.length){var m=Date.now(),n=vc.shift();n.Vc(n.Mb);if(xc){var t=xc,r=0==t%1?t-1:Math.floor(t);xc=n.vd?r:(8*t+(r+.5))/9}x('main loop blocker "'+
n.name+'" took '+(Date.now()-m)+" ms");f.setStatus&&(m=f.statusMessage||"Please wait...",n=xc,t=wc.yd,n?n<t?f.setStatus(m+" ("+(t-n)+"/"+t+")"):f.setStatus(m):f.setStatus(""));g()&&setTimeout(zc,0)}else g()&&(uc=uc+1|0,1==sc&&1<tc&&0!=uc%tc?oc():(0==sc&&(yc=cd()),"undefined"!==typeof Jc&&S&&!Jc.wd&&!S.attributes.zd&&S.Ib.commit&&S.Ib.commit(),ya||f.preMainLoop&&!1===f.preMainLoop()||(lc(a),f.postMainLoop&&f.postMainLoop()),g()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.dd&&SDL.audio.dd(),oc())))};
e||(b&&0<b?bd(0,1E3/b):bd(1,1),oc());if(c)throw"unwind";}var fd={};function gd(){if(!hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in fd)void 0===fd[b]?delete a[b]:a[b]=fd[b];var c=[];for(b in a)c.push(b+"="+a[b]);hd=c}return hd}var hd;
function jd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,k){b.drawElementsInstancedANGLE(c,d,e,g,k)})}
function kd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function ld(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var md=1,nd=[],T=[],od=[],U=[],pd=[],Lc=[],qd={},rd=4;function V(a){sd||(sd=a)}
function td(a){for(var b=md++,c=a.length;c<b;c++)a[c]=null;return b}function Kc(a,b){a.vc||(a.vc=a.getContext,a.getContext=function(d,e){e=a.vc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.zc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?ud(c,b):0}function ud(a,b){var c=td(Lc),d={Cd:c,attributes:b,version:b.zc,Ib:a};a.canvas&&(a.canvas.td=d);Lc[c]=d;("undefined"===typeof b.Uc||b.Uc)&&vd(d);return c}
function vd(a){a||(a=S);if(!a.Yc){a.Yc=!0;var b=a.Ib;jd(b);kd(b);ld(b);b.xd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Dd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.rc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.rc)b.rc=b.getExtension("EXT_disjoint_timer_query");b.Gd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Jc={},S,sd;function wd(a,b,c,d){for(var e=0;e<a;e++){var g=Q[c](),k=g&&td(d);g?(g.name=k,d[k]=g):V(1282);D[b+4*e>>2]=k}}
function xd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Q.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>S.version){V(1282);return}c=2*(Q.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>S.version){V(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Q.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":V(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:V(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){V(1280);l("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:V(1280);l("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}D[b>>2]=c}else V(1281)}
function yd(a){var b=Ga(a)+1,c=Ba(b);Fa(a,F,c,b);return c}function zd(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Ad(a){a-=5120;return 0==a?C:1==a?F:2==a?ta:4==a?D:6==a?va:5==a||28922==a||28520==a||30779==a||30782==a?La:Ka}function Bd(a){var b=Q.Tc;if(b){var c=b.Lb[a];"number"===typeof c&&(b.Lb[a]=c=Q.getUniformLocation(b,b.Jc[a]+(0<c?"["+c+"]":"")));return c}V(1282)}var Cd=[];
function Dd(a,b,c,d){this.id=a;this.y=this.x=0;this.fc=!1;this.Ic=this.Hc=0;this.width=b;this.height=c;this.Gc=b;this.Fc=c;this.title=d;this.attributes=Ed;this.Pb={208897:212993,208898:0,208899:0};this.buttons=0;this.keys=[];this.bc=[];this.Nb=this.Qb=this.cc=this.Wb=this.Bb=this.Ob=this.Vb=this.uc=this.Lc=this.$b=this.Hb=this.Mc=this.title=null}function W(a){return 0>=a||!X?null:X[a-1]}
var Fd=null,Gd=null,Y=null,X=null,Hd=null,Id=null,Ed=null,Jd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Kd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Ld(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function Md(a){Y&&Y.Nb&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||H(Y.Nb)(Y.id,a))}function Nd(a,b){if(Y){var c=Kd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.bc[a]=b;Y.Qb&&(d&&(b=2),H(Y.Qb)(Y.id,c,a,b,Ld()))}}}
function Od(){Pd()}function Qd(){Pd()}function Rd(a){Nd(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function Sd(a){Nd(a.keyCode,0)}function Td(){if(Y)for(var a=0;a<Y.bc.length;++a)Y.bc[a]&&Nd(a,0)}function Ud(a){Y&&(Zc(a),a.target==f.canvas&&Y.Ob&&H(Y.Ob)(Y.id,Vc,Wc))}function Vd(a){Y&&a.target==f.canvas&&Y.Bb&&H(Y.Bb)(Y.id,1)}function Wd(a){Y&&a.target==f.canvas&&Y.Bb&&H(Y.Bb)(Y.id,0)}
function Xd(a,b){if(Y&&(Zc(a),a.target==f.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Vb&&H(Y.Vb)(Y.id,c,b,Ld())}}function Yd(a){Y&&Xd(a,1)}function Zd(a){Y&&Xd(a,0)}
function $d(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Wb&&a.target==f.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;H(Y.Wb)(Y.id,b,c);a.preventDefault()}}var Z={},ae=null,be=null;
function Pd(){if(uc!==be||!uc){ae=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;be=uc;for(var a=0;a<ae.length;++a){var b=ae[a];if(b){Z[a]||(x("glfw joystick connected:",a),Z[a]={id:Aa(pb(b.id)),Rc:b.buttons.length,Pc:b.axes.length,buttons:Aa(Array(b.buttons.length)),axes:Aa(Array(4*b.axes.length))});for(var c=Z[a],d=0;d<b.buttons.length;++d)B(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)B(c.axes+4*d,b.axes[d],"float")}else Z[a]&&
(x("glfw joystick disconnected",a),ce(Z[a].id),ce(Z[a].buttons),ce(Z[a].axes),delete Z[a])}}}
function ee(a){function b(m){var n="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),t=new FileReader;t.onloadend=function(w){if(2!=t.readyState)++g,x("failed to read dropped file: "+m.name+": "+t.error);else{var v=new Uint8Array(w.target.result);var h=h||{};h.flags=h.flags||577;w=Tb(n,h.flags,h.mode);if("string"===typeof v){var u=new Uint8Array(Ga(v)+1);v=Fa(v,u,0,u.length);Xb(w,u,0,v,void 0,h.Sc)}else if(ArrayBuffer.isView(v))Xb(w,v,0,v.byteLength,void 0,h.Sc);else throw Error("Unsupported data type");
Vb(w);if(++g===e){H(Y.cc)(Y.id,e,c);for(h=0;h<d.length;++h)ce(d[h]);ce(c)}}};t.readAsArrayBuffer(m);var r=Aa(pb(n));d.push(r);B(c+4*k,r,"i8*")}if(Y&&Y.cc&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Aa(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,g=0;ac("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function fe(a){if(Y&&Y.cc)return a.preventDefault(),!1}
function ge(a){!Bc&&f.canvas.requestPointerLock&&(f.canvas.requestPointerLock(),a.preventDefault())}function he(a){return 0===a%4&&(0!==a%100||0===a%400)}function ie(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var je=[31,29,31,30,31,30,31,31,30,31,30,31],ke=[31,28,31,30,31,30,31,31,30,31,30,31];
function le(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(he(a.getFullYear())?je:ke)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function me(a,b,c,d){function e(h,u,y){for(h="number"===typeof h?h.toString():h||"";h.length<u;)h=y[0]+h;return h}function g(h,u){return e(h,u,"0")}function k(h,u){function y(R){return 0>R?-1:0<R?1:0}var A;0===(A=y(h.getFullYear()-u.getFullYear()))&&0===(A=y(h.getMonth()-u.getMonth()))&&(A=y(h.getDate()-u.getDate()));return A}function m(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=le(new Date(h.sb+1900,0,1),h.Zb);var u=new Date(h.getFullYear()+1,0,4),y=m(new Date(h.getFullYear(),0,4));u=m(u);return 0>=k(y,h)?0>=k(u,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var t=D[d+40>>2];d={pd:D[d>>2],od:D[d+4>>2],Xb:D[d+8>>2],Kb:D[d+12>>2],Gb:D[d+16>>2],sb:D[d+20>>2],Yb:D[d+24>>2],Zb:D[d+28>>2],Jd:D[d+32>>2],nd:D[d+
36>>2],qd:t?Ea(t):""};c=Ea(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");t={"%a":function(h){return w[h.Yb].substring(0,3)},"%A":function(h){return w[h.Yb]},"%b":function(h){return v[h.Gb].substring(0,3)},"%B":function(h){return v[h.Gb]},"%C":function(h){return g((h.sb+1900)/100|0,2)},"%d":function(h){return g(h.Kb,2)},"%e":function(h){return e(h.Kb,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return g(h.Xb,
2)},"%I":function(h){h=h.Xb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Kb+ie(he(h.sb+1900)?je:ke,h.Gb-1),3)},"%m":function(h){return g(h.Gb+1,2)},"%M":function(h){return g(h.od,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Xb&&12>h.Xb?"AM":"PM"},"%S":function(h){return g(h.pd,2)},"%t":function(){return"\t"},"%u":function(h){return h.Yb||7},"%U":function(h){var u=new Date(h.sb+1900,0,1),y=0===u.getDay()?u:le(u,7-u.getDay());h=new Date(h.sb+1900,h.Gb,h.Kb);return 0>
k(y,h)?g(Math.ceil((31-y.getDate()+(ie(he(h.getFullYear())?je:ke,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(y,u)?"01":"00"},"%V":function(h){var u=new Date(h.sb+1901,0,4),y=m(new Date(h.sb+1900,0,4));u=m(u);var A=le(new Date(h.sb+1900,0,1),h.Zb);return 0>k(A,y)?"53":0>=k(u,A)?"01":g(Math.ceil((y.getFullYear()<h.sb+1900?h.Zb+32-y.getDate():h.Zb+1-y.getDate())/7),2)},"%w":function(h){return h.Yb},"%W":function(h){var u=new Date(h.sb,0,1),y=1===u.getDay()?u:le(u,0===u.getDay()?1:7-u.getDay()+1);h=
new Date(h.sb+1900,h.Gb,h.Kb);return 0>k(y,h)?g(Math.ceil((31-y.getDate()+(ie(he(h.getFullYear())?je:ke,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(y,u)?"01":"00"},"%y":function(h){return(h.sb+1900).toString().substring(2)},"%Y":function(h){return h.sb+1900},"%z":function(h){h=h.nd;var u=0<=h;h=Math.abs(h)/60;return(u?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.qd},"%%":function(){return"%"}};for(r in t)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=pb(c,
!1);if(r.length>b)return 0;C.set(r,a);return r.length-1}function Gb(a,b,c,d){a||(a=this);this.parent=a;this.wb=a.wb;this.Jb=null;this.id=Ab++;this.name=b;this.mode=c;this.pb={};this.qb={};this.rdev=d}
Object.defineProperties(Gb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},ad:{get:function(){return 16384===(this.mode&61440)}},$c:{get:function(){return 8192===(this.mode&61440)}}});Yb();M=Array(4096);Nb(L,"/");O("/tmp");O("/home");O("/home/web_user");
(function(){O("/dev");nb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Pb("/dev/null",259);mb(1280,qb);mb(1536,rb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=jb();P("/dev","random",a);P("/dev","urandom",a);O("/dev/shm");O("/dev/shm/tmp")})();
(function(){O("/proc");var a=O("/proc/self");O("/proc/self/fd");Nb({wb:function(){var b=tb(a,"fd",16895,73);b.pb={lookup:function(c,d){var e=zb[+d];if(!e)throw new J(8);c={parent:null,wb:{Bc:"fake"},pb:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();f.FS_createPath=ac;f.FS_createDataFile=cc;f.FS_createPreloadedFile=fc;f.FS_createLazyFile=ec;f.FS_createDevice=P;f.FS_unlink=Rb;f.requestFullscreen=function(a,b){Pc(a,b)};f.requestAnimationFrame=function(a){Uc(a)};
f.setCanvasSize=function(a,b,c){ad(a,b,c)};f.pauseMainLoop=function(){oc=null;pc++};f.resumeMainLoop=function(){pc++;var a=sc,b=tc,c=qc;qc=null;dd(c,0,!1,rc,!0);bd(a,b);oc()};f.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};f.createContext=function(a,b,c,d){return Ic(a,b,c,d)};for(var Q,ne=new Float32Array(288),oe=0;288>oe;++oe)Cd[oe]=ne.subarray(0,oe+1);
function pb(a,b){var c=Array(Ga(a)+1);a=Fa(a,c,0,c.length);b&&(c.length=a);return c}
var qe={na:function(a){return Ba(a+16)+16},ma:function(a,b,c){(new eb(a)).Xc(b,c);fb++;throw a;},ca:function(a,b,c){ic=c;try{var d=kc(a);switch(b){case 0:var e=jc();return 0>e?-28:Tb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=jc(),d.flags|=e,0;case 12:return e=jc(),ta[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return D[pe()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof hc&&g instanceof J||z(g),-g.xb}},cb:function(a,
b,c){ic=c;try{var d=kc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=jc();return D[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=jc();if(!d.qb.Zc)throw new J(59);return d.qb.Zc(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:z("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof hc&&g instanceof J||z(g),-g.xb}},db:function(a,
b,c){ic=c;try{var d=Ea(a),e=c?jc():0;return Tb(d,b,e).fd}catch(g){return"undefined"!==typeof hc&&g instanceof J||z(g),-g.xb}},ba:function(){z("")},Xa:function(a,b,c){F.copyWithin(a,b,b+c)},Ya:function(a){var b=F.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{xa.grow(Math.min(2147483648,d)-Ja.byteLength+65535>>>16);Ma();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},ha:function(a,
b,c){a=H(a);dd(a,b,c)},$a:function(a,b){var c=0;gd().forEach(function(d,e){var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<d.length;++g)C[e++>>0]=d.charCodeAt(g);C[e>>0]=0;c+=d.length+1});return 0},ab:function(a,b){var c=gd();D[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});D[b>>2]=d;return 0},G:function(a){ed(a)},ea:function(a){try{var b=kc(a);Vb(b);return 0}catch(c){return"undefined"!==typeof hc&&c instanceof J||z(c),c.xb}},bb:function(a,b,c,d){try{a:{for(var e=kc(a),g=a=0;g<c;g++){var k=D[b+
(8*g+4)>>2],m=e,n=D[b+8*g>>2],t=k,r=void 0,w=C;if(0>t||0>r)throw new J(28);if(null===m.fd)throw new J(8);if(1===(m.flags&2097155))throw new J(8);if(16384===(m.node.mode&61440))throw new J(31);if(!m.qb.read)throw new J(28);var v="undefined"!==typeof r;if(!v)r=m.position;else if(!m.seekable)throw new J(70);var h=m.qb.read(m,w,n,t,r);v||(m.position+=h);var u=h;if(0>u){var y=-1;break a}a+=u;if(u<k)break}y=a}D[d>>2]=y;return 0}catch(A){return"undefined"!==typeof hc&&A instanceof J||z(A),A.xb}},Wa:function(a,
b,c,d,e){try{var g=kc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Wb(g,a,d);ua=[g.position>>>0,(E=g.position,1<=+Math.abs(E)?0<E?(Math.min(+Math.floor(E/4294967296),4294967295)|0)>>>0:~~+Math.ceil((E-+(~~E>>>0))/4294967296)>>>0:0)];D[e>>2]=ua[0];D[e+4>>2]=ua[1];g.hc&&0===a&&0===d&&(g.hc=null);return 0}catch(k){return"undefined"!==typeof hc&&k instanceof J||z(k),k.xb}},da:function(a,b,c,d){try{a:{for(var e=kc(a),g=a=0;g<c;g++){var k=Xb(e,C,D[b+8*g>>2],D[b+(8*g+
4)>>2],void 0);if(0>k){var m=-1;break a}a+=k}m=a}D[d>>2]=m;return 0}catch(n){return"undefined"!==typeof hc&&n instanceof J||z(n),n.xb}},t:function(a){Q.activeTexture(a)},C:function(a,b){Q.attachShader(T[a],U[b])},i:function(a,b){35051==a?Q.qc=b:35052==a&&(Q.ac=b);Q.bindBuffer(a,nd[b])},f:function(a,b){Q.bindTexture(a,od[b])},l:function(a){Q.bindVertexArray(pd[a])},wa:function(a){Q.blendEquation(a)},xa:function(a,b){Q.blendEquationSeparate(a,b)},L:function(a,b,c,d){Q.blendFuncSeparate(a,b,c,d)},x:function(a,
b,c,d){2<=S.version?c?Q.bufferData(a,F,d,c,b):Q.bufferData(a,b,d):Q.bufferData(a,c?F.subarray(c,c+b):b,d)},oa:function(a){Q.clear(a)},ga:function(a,b,c){Q.clearBufferfv(a,b,va,c>>2)},pa:function(a,b,c,d){Q.clearColor(a,b,c,d)},D:function(a){Q.compileShader(U[a])},S:function(){var a=td(T),b=Q.createProgram();b.name=a;b.Tb=b.Rb=b.Sb=0;b.mc=1;T[a]=b;return a},u:function(a){var b=td(U);U[b]=Q.createShader(a);return b},Aa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=nd[d];e&&(Q.deleteBuffer(e),
e.name=0,nd[d]=null,d==Q.qc&&(Q.qc=0),d==Q.ac&&(Q.ac=0))}},za:function(a){if(a){var b=T[a];b?(Q.deleteProgram(b),b.name=0,T[a]=null):V(1281)}},A:function(a){if(a){var b=U[a];b?(Q.deleteShader(b),U[a]=null):V(1281)}},sa:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2],e=od[d];e&&(Q.deleteTexture(e),e.name=0,od[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=D[b+4*c>>2];Q.deleteVertexArray(pd[d]);pd[d]=null}},B:function(a,b){Q.detachShader(T[a],U[b])},e:function(a){Q.disable(a)},eb:function(a,
b,c){Q.drawArrays(a,b,c)},ya:function(a,b,c,d){Q.drawElements(a,b,c,d)},g:function(a){Q.enable(a)},p:function(a){Q.enableVertexAttribArray(a)},y:function(a,b){wd(a,b,"createBuffer",nd)},J:function(a,b){wd(a,b,"createTexture",od)},O:function(a,b){wd(a,b,"createVertexArray",pd)},z:function(a,b){return Q.getAttribLocation(T[a],Ea(b))},a:function(a,b){xd(a,b)},qa:function(a,b,c,d){a=Q.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?Fa(a,F,d,b):0;c&&(D[c>>2]=b)},m:function(a,b,c){if(c)if(a>=
md)V(1281);else if(a=T[a],35716==b)a=Q.getProgramInfoLog(a),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b){if(!a.Tb)for(b=0;b<Q.getProgramParameter(a,35718);++b)a.Tb=Math.max(a.Tb,Q.getActiveUniform(a,b).name.length+1);D[c>>2]=a.Tb}else if(35722==b){if(!a.Rb)for(b=0;b<Q.getProgramParameter(a,35721);++b)a.Rb=Math.max(a.Rb,Q.getActiveAttrib(a,b).name.length+1);D[c>>2]=a.Rb}else if(35381==b){if(!a.Sb)for(b=0;b<Q.getProgramParameter(a,35382);++b)a.Sb=Math.max(a.Sb,Q.getActiveUniformBlockName(a,
b).length+1);D[c>>2]=a.Sb}else D[c>>2]=Q.getProgramParameter(a,b);else V(1281)},ra:function(a,b,c,d){a=Q.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?Fa(a,F,d,b):0;c&&(D[c>>2]=b)},n:function(a,b,c){c?35716==b?(a=Q.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),D[c>>2]=a?a.length+1:0):35720==b?(a=Q.getShaderSource(U[a]),D[c>>2]=a?a.length+1:0):D[c>>2]=Q.getShaderParameter(U[a],b):V(1281)},Ba:function(a){var b=qd[a];if(!b){switch(a){case 7939:b=Q.getSupportedExtensions()||
[];b=b.concat(b.map(function(d){return"GL_"+d}));b=yd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Q.getParameter(a))||V(1280);b=b&&yd(b);break;case 7938:b=Q.getParameter(7938);b=2<=S.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=yd(b);break;case 35724:b=Q.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=yd(b);break;default:V(1280)}qd[a]=b}return b},b:function(a,
b){b=Ea(b);if(a=T[a]){var c=a,d=c.Lb,e=c.Kc,g;if(!d)for(c.Lb=d={},c.Jc={},g=0;g<Q.getProgramParameter(c,35718);++g){var k=Q.getActiveUniform(c,g);var m=k.name;k=k.size;var n=zd(m);n=0<n?m.slice(0,n):m;var t=c.mc;c.mc+=k;e[n]=[k,t];for(m=0;m<k;++m)d[t]=m,c.Jc[t++]=n}c=a.Lb;d=0;e=b;g=zd(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Kc[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||Q.getUniformLocation(a,b)))return d}else V(1281);return-1},k:function(a){return Q.isEnabled(a)},Q:function(a){a=T[a];
Q.linkProgram(a);a.Lb=0;a.Kc={}},ta:function(a,b){3317==a&&(rd=b);Q.pixelStorei(a,b)},N:function(a,b,c,d){Q.scissor(a,b,c,d)},E:function(a,b,c,d){for(var e="",g=0;g<b;++g){var k=d?D[d+4*g>>2]:-1;e+=Ea(D[c+4*g>>2],0>k?void 0:k)}Q.shaderSource(U[a],e)},I:function(a,b,c,d,e,g,k,m,n){if(2<=S.version)if(Q.ac)Q.texImage2D(a,b,c,d,e,g,k,m,n);else if(n){var t=Ad(m);Q.texImage2D(a,b,c,d,e,g,k,m,t,n>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else Q.texImage2D(a,b,c,d,e,g,k,m,null);else{t=Q;var r=t.texImage2D;if(n){var w=
Ad(m),v=31-Math.clz32(w.BYTES_PER_ELEMENT),h=rd;n=w.subarray(n>>v,n+e*(d*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[k-6402]||1)*(1<<v)+h-1&-h)>>v)}else n=null;r.call(t,a,b,c,d,e,g,k,m,n)}},h:function(a,b,c){Q.texParameteri(a,b,c)},j:function(a,b){Q.uniform1f(Bd(a),b)},q:function(a,b){Q.uniform1i(Bd(a),b)},fa:function(a,b,c){Q.uniform2f(Bd(a),b,c)},va:function(a,b,c,d){if(2<=S.version)Q.uniformMatrix4fv(Bd(a),!!c,va,d>>2,16*b);else{if(18>=b){var e=Cd[16*b-1],g=va;d>>=2;for(var k=
0;k<16*b;k+=16){var m=d+k;e[k]=g[m];e[k+1]=g[m+1];e[k+2]=g[m+2];e[k+3]=g[m+3];e[k+4]=g[m+4];e[k+5]=g[m+5];e[k+6]=g[m+6];e[k+7]=g[m+7];e[k+8]=g[m+8];e[k+9]=g[m+9];e[k+10]=g[m+10];e[k+11]=g[m+11];e[k+12]=g[m+12];e[k+13]=g[m+13];e[k+14]=g[m+14];e[k+15]=g[m+15]}}else e=va.subarray(d>>2,d+64*b>>2);Q.uniformMatrix4fv(Bd(a),!!c,e)}},s:function(a){a=T[a];Q.useProgram(a);Q.Tc=a},o:function(a,b,c,d,e,g){Q.vertexAttribPointer(a,b,c,!!d,e,g)},r:function(a,b,c,d){Q.viewport(a,b,c,d)},d:function(){},_:function(a,
b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var g=e+1;if(0>=a||0>=b)g=0;else{d?Pc():ad(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Ed[139265];e==X.length&&(d?f.Ab=Ic(f.canvas,!0,!0,{antialias:1<Ed[135181],depth:0<Ed[135173],stencil:0<Ed[135174],alpha:0<Ed[135172]}):gc());!f.Ab&&d?g=0:(a=new Dd(g,a,b,c),g-1==X.length?X.push(a):X[g-1]=a,Y=a,g=a.id)}return g},Ca:function(){throw"glfwCreateWindowSurface is not implemented.";
},Ga:function(a){a:{if(a=W(a)){a.$b&&H(a.$b)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}f.Ab=void 0}a=void 0}return a},Ea:function(){},Ka:function(){},aa:function(a,b,c){B(b,Vc,"double");B(c,Wc,"double")},fb:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.width,e=a.height;b&&B(b,d,"i32");c&&B(c,e,"i32")},Ra:function(a,b){if(a=W(a)){switch(b){case 208897:a.Pb[b]=Bc?212995:212993}return a.Pb[b]}},Na:function(a,b){Pd();if((a=Z[a])&&a.axes)return B(b,a.Pc,
"i32"),a.axes;B(b,0,"i32")},Ma:function(a,b){Pd();if((a=Z[a])&&a.buttons)return B(b,a.Rc,"i32"),a.buttons;B(b,0,"i32")},Ua:function(a,b,c){B(b,0,"i32");B(c,0,"i32")},Va:function(a){B(a,1,"i32");Hd||(Hd=Ba(4),B(Hd,1,"i32"));return Hd},w:function(a,b){return(a=W(a))?0<(a.buttons&1<<b):0},_a:function(){return cd()/1E3-Id},Ta:function(){return 0},V:function(a,b){return(a=W(a))?a.attributes[b]:0},$:function(a,b,c){var d=0,e=0;if(a=W(a))d=a.x,e=a.y;b&&B(b,d,"i32");c&&B(c,e,"i32")},H:function(a,b,c){var d=
0,e=0;if(a=W(a))d=a.width,e=a.height;b&&B(b,d,"i32");c&&B(c,e,"i32")},la:function(){if(X)return 1;Id=cd()/1E3;Ed=Jd;X=[];Y=null;window.addEventListener("gamepadconnected",Od,!0);window.addEventListener("gamepaddisconnected",Qd,!0);window.addEventListener("keydown",Rd,!0);window.addEventListener("keypress",Md,!0);window.addEventListener("keyup",Sd,!0);window.addEventListener("blur",Td,!0);f.canvas.addEventListener("touchmove",Ud,!0);f.canvas.addEventListener("touchstart",Yd,!0);f.canvas.addEventListener("touchcancel",
Zd,!0);f.canvas.addEventListener("touchend",Zd,!0);f.canvas.addEventListener("mousemove",Ud,!0);f.canvas.addEventListener("mousedown",Yd,!0);f.canvas.addEventListener("mouseup",Zd,!0);f.canvas.addEventListener("wheel",$d,!0);f.canvas.addEventListener("mousewheel",$d,!0);f.canvas.addEventListener("mouseenter",Vd,!0);f.canvas.addEventListener("mouseleave",Wd,!0);f.canvas.addEventListener("drop",ee,!0);f.canvas.addEventListener("dragover",fe,!0);$c.push(function(a,b){if(Y){var c=!0;document.fullscreen||
document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.Hc=Y.x,Y.Ic=Y.y,Y.Gc=Y.width,Y.Fc=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.fc=!0):1==Y.fc?(Y.x=Y.Hc,Y.y=Y.Ic,Y.width=Y.Gc,Y.height=Y.Fc,Y.fc=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(ad(Y.width,Y.height,!0),Y&&Y.Hb&&H(Y.Hb)(Y.id,Y.width,Y.height),Y&&Y.uc&&H(Y.uc)(Y.id,Y.width,Y.height))}});return 1},v:function(){},ia:function(){},K:function(a,b){if(a=W(a)){var c=a.Nb;a.Nb=b;b=c}else b=
null;return b},La:function(){},Pa:function(){},Ia:function(a,b){a=W(a);if(!a)return null;var c=a.Bb;a.Bb=b;return c},Sa:function(){},ka:function(a,b){if(a=W(a)){var c=a.Ob;a.Ob=b;b=c}else b=null;return b},F:function(a){var b=Fd;Fd=a;return b},Oa:function(a,b,c){if(a=W(a))switch(b){case 208897:switch(c){case 212993:a.Pb[b]=c;f.canvas.removeEventListener("click",ge,!0);f.canvas.exitPointerLock();break;case 212994:x("glfwSetInputMode called with GLFW_CURSOR_HIDDEN value not implemented.");break;case 212995:a.Pb[b]=
c;f.canvas.addEventListener("click",ge,!0);f.canvas.requestPointerLock();break;default:x("glfwSetInputMode called with unknown value parameter value: "+c+".")}break;case 208898:x("glfwSetInputMode called with GLFW_STICKY_KEYS mode not implemented.");break;case 208899:x("glfwSetInputMode called with GLFW_STICKY_MOUSE_BUTTONS mode not implemented.");break;default:x("glfwSetInputMode called with unknown mode parameter value: "+b+".")}},P:function(a,b){if(a=W(a)){var c=a.Qb;a.Qb=b;b=c}else b=null;return b},
ua:function(a){var b=Gd;Gd=a;return b},U:function(a,b){if(a=W(a)){var c=a.Vb;a.Vb=b;b=c}else b=null;return b},R:function(a,b){if(a=W(a)){var c=a.Wb;a.Wb=b;b=c}else b=null;return b},Ja:function(a,b){if(a=W(a)){var c=a.$b;a.$b=b;b=c}else b=null;return b},Qa:function(a,b){a=W(a);if(!a)return null;var c=a.Lc;a.Lc=b;return c},Z:function(a,b,c){if(a=W(a))a.x=b,a.y=c},Ha:function(a,b){a=W(a);if(!a)return null;var c=a.Mc;a.Mc=b;return c},W:function(a,b,c){if(a=W(a))Y.id==a.id&&(b==screen.width&&c==screen.height?
Pc():(Qc(),ad(b,c),a.width=b,a.height=c)),a.Hb&&H(a.Hb)(a.id,b,c)},Y:function(a,b){if(a=W(a)){var c=a.Hb;a.Hb=b;b=c}else b=null;return b},Da:function(a,b){if(a=W(a))a.title=Ea(b),Y.id==a.id&&(document.title=a.title)},Fa:function(){},T:function(){},X:function(a){a=Math.abs(a);0==a?bd(0,0):bd(1,a)},ja:function(){window.removeEventListener("gamepadconnected",Od,!0);window.removeEventListener("gamepaddisconnected",Qd,!0);window.removeEventListener("keydown",Rd,!0);window.removeEventListener("keypress",
Md,!0);window.removeEventListener("keyup",Sd,!0);window.removeEventListener("blur",Td,!0);f.canvas.removeEventListener("touchmove",Ud,!0);f.canvas.removeEventListener("touchstart",Yd,!0);f.canvas.removeEventListener("touchcancel",Zd,!0);f.canvas.removeEventListener("touchend",Zd,!0);f.canvas.removeEventListener("mousemove",Ud,!0);f.canvas.removeEventListener("mousedown",Yd,!0);f.canvas.removeEventListener("mouseup",Zd,!0);f.canvas.removeEventListener("wheel",$d,!0);f.canvas.removeEventListener("mousewheel",
$d,!0);f.canvas.removeEventListener("mouseenter",Vd,!0);f.canvas.removeEventListener("mouseleave",Wd,!0);f.canvas.removeEventListener("drop",ee,!0);f.canvas.removeEventListener("dragover",fe,!0);f.canvas.width=f.canvas.height=1;Y=X=null},c:function(a,b){Ed[a]=b},Za:function(a,b,c,d){return me(a,b,c,d)}};
(function(){function a(e){f.asm=e.exports;xa=f.asm.gb;Ma();Na=f.asm.kb;Pa.unshift(f.asm.hb);Ya("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return bb().then(function(g){return WebAssembly.instantiate(g,d)}).then(function(g){return g}).then(e,function(g){l("failed to asynchronously prepare wasm: "+g);z(g)})}var d={a:qe};Xa("wasm-instantiate");if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return sa||
"function"!==typeof WebAssembly.instantiateStreaming||Za()||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){l("wasm streaming compile failed: "+g);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.hb).apply(null,arguments)};
var Ba=f._malloc=function(){return(Ba=f._malloc=f.asm.ib).apply(null,arguments)},ce=f._free=function(){return(ce=f._free=f.asm.jb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.lb).apply(null,arguments)};var pe=f.___errno_location=function(){return(pe=f.___errno_location=f.asm.mb).apply(null,arguments)},Ia=f.stackAlloc=function(){return(Ia=f.stackAlloc=f.asm.nb).apply(null,arguments)};f.addRunDependency=Xa;f.removeRunDependency=Ya;f.FS_createPath=ac;f.FS_createDataFile=cc;
f.FS_createPreloadedFile=fc;f.FS_createLazyFile=ec;f.FS_createDevice=P;f.FS_unlink=Rb;var re;function na(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Wa=function se(){re||te();re||(Wa=se)};
function te(a){function b(){if(!re&&(re=!0,f.calledRun=!0,!ya)){f.noFSInit||Zb||(Zb=!0,Yb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?P("/dev","stdin",f.stdin):Qb("/dev/tty","/dev/stdin"),f.stdout?P("/dev","stdout",null,f.stdout):Qb("/dev/tty","/dev/stdout"),f.stderr?P("/dev","stderr",null,f.stderr):Qb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin",0),Tb("/dev/stdout",1),Tb("/dev/stderr",1));Bb=!1;cb(Pa);cb(Qa);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(ue){var c=a,d=f._main;
c=c||[];var e=c.length+1,g=Ia(4*(e+1));D[g>>2]=Ha(ca);for(var k=1;k<e;k++)D[(g>>2)+k]=Ha(c[k-1]);D[(g>>2)+e]=0;try{var m=d(e,g);ed(m)}catch(n){db(n)}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ra.unshift(c);cb(Ra)}}a=a||ba;if(!(0<Ua)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ta();cb(Oa);0<Ua||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},
1);b()},1)):b())}}f.run=te;function ed(a){za=a;noExitRuntime||0<oa||(Sa=!0);za=a;if(!(noExitRuntime||0<oa)){if(f.onExit)f.onExit(a);ya=!0}da(a,new na(a))}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();var ue=!0;f.noInitialRun&&(ue=!1);te();
